ProyectoFinal/Controllers/CarritoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Proyecto.Models;
using ProyectoFinal.Data;
using ProyectoFinal.Models;

namespace ProyectoFinal.Controllers
{
    public class CarritoController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CarritoController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Carrito
        public IActionResult Index()
        {
            //var applicationDbContext = _context.Carrito.Include(c => c.Producto);
            //return View(await applicationDbContext.ToListAsync());

            ViewData["Categorias"] = (from c in _context.Categorias select c);

            IPHostEntry heserver = Dns.GetHostEntry(Dns.GetHostName());
            var ip = heserver.AddressList[1].ToString();

            var carrito = (from n in _context.Carrito.Include("Producto")
                           where n.Sesion == ip
                          select n);

            return View(carrito.ToList());
        }

        [Authorize]
        public async Task<IActionResult> Comprar()
        {
            ViewData["Categorias"] = (from c in _context.Categorias select c);

            IPHostEntry heserver = Dns.GetHostEntry(Dns.GetHostName());
            var ip = heserver.AddressList[1].ToString();

            var carrito = (from n in _context.Carrito.Include("Producto")
                           where n.Sesion == ip
                           select n).ToList();

            var cliente = (from n in _context.Clientes
                           where n.EmailCliente == User.Identity.Name
                           select n).ToList();

            var pedido = new Pedidos
            {
                ClienteID = cliente[0].ClienteID,
                EstatusID = 1,
            };
            _context.Add(pedido);
            await _context.SaveChangesAsync();

            foreach (var item in carrito)
            {
                var detPedido = new DetallePedido
                {
                    PedidoID = pedido.PedidoID,
                    ProductoID = item.ProductoID,
                    PrecioVenta = item.Precio,
                    CantidadVendida = item.Cantidad,
                    DescuentoVenta = item.Descuento,
                };

                _context.Add(detPedido);
                await _context.SaveChangesAsync();

                Productos objProducto = _context.Productos.Find(item.ProductoID);
                objProducto.Existencia = objProducto.Existencia - item.Cantidad;
                _context.Carrito.Update(item);
                await _context.SaveChangesAsync();

                // Eliminamos el item que se registró 
                _context.Carrito.Remove(item);
                await _context.SaveChangesAsync();
            }

            return RedirectToAction("PedidosCliente", "Pedidos");
        }

        // POST: Carrito/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        public async Task<IActionResult> Agregar( int idProducto, int cantidad, decimal precio, decimal descu)
        {
            ViewData["Categorias"] = (from c in _context.Categorias select c);

            IPHostEntry heserver = Dns.GetHostEntry(Dns.GetHostName());
            var ip = heserver.AddressList[1].ToString();

            var carrito = new Carrito
            {
                ProductoID = idProducto,
                Sesion = ip,
                Cantidad = cantidad,
                Precio = precio,
                Descuento = Decimal.ToInt32(descu),
            };

            _context.Add(carrito);
            await _context.SaveChangesAsync();
            
            /*ViewData["cantidadCarrito"] = (from n in _context.Carrito
                                           where n.Sesion == ip
                                           select n.ProductoID
                                           ).Count();*/

            return RedirectToAction("Index","Home");
        }
        
        
        // POST: Carrito/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            ViewData["Categorias"] = (from c in _context.Categorias select c);

            var carrito = await _context.Carrito.FindAsync(id);
            _context.Carrito.Remove(carrito);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CarritoExists(int id)
        {
            return _context.Carrito.Any(e => e.CarritoID == id);
        }
    }
}

ProyectoFinal/Controllers/EstatusPedidoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Proyecto.Models;
using ProyectoFinal.Data;

namespace ProyectoFinal.Controllers
{
    [Authorize(Roles = "Administrador")]
    public class EstatusPedidoController : Controller
    {
        private readonly ApplicationDbContext _context;

        public EstatusPedidoController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: EstatusPedido
        public async Task<IActionResult> Index()
        {
            ViewData["Categorias"] = (from c in _context.Categorias select c);
            return View(await _context.EstatusPedido.ToListAsync());
        }

        // GET: EstatusPedido/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            ViewData["Categorias"] = (from c in _context.Categorias select c);
            if (id == null)
            {
                return NotFound();
            }

            var estatusPedido = await _context.EstatusPedido
                .FirstOrDefaultAsync(m => m.EstatusID == id);
            if (estatusPedido == null)
            {
                return NotFound();
            }

            return View(estatusPedido);
        }

        // GET: EstatusPedido/Create
        public IActionResult Create()
        {
            ViewData["Categorias"] = (from c in _context.Categorias select c);
            return View();
        }

        // POST: EstatusPedido/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("EstatusID,DescEstatus")] EstatusPedido estatusPedido)
        {
            ViewData["Categorias"] = (from c in _context.Categorias select c);
            if (ModelState.IsValid)
            {
                _context.Add(estatusPedido);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(estatusPedido);
        }

        // GET: EstatusPedido/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            ViewData["Categorias"] = (from c in _context.Categorias select c);
            if (id == null)
            {
                return NotFound();
            }

            var estatusPedido = await _context.EstatusPedido.FindAsync(id);
            if (estatusPedido == null)
            {
                return NotFound();
            }
            return View(estatusPedido);
        }

        // POST: EstatusPedido/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("EstatusID,DescEstatus")] EstatusPedido estatusPedido)
        {
            ViewData["Categorias"] = (from c in _context.Categorias select c);
            if (id != estatusPedido.EstatusID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(estatusPedido);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EstatusPedidoExists(estatusPedido.EstatusID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(estatusPedido);
        }

        // GET: EstatusPedido/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            ViewData["Categorias"] = (from c in _context.Categorias select c);
            if (id == null)
            {
                return NotFound();
            }

            var estatusPedido = await _context.EstatusPedido
                .FirstOrDefaultAsync(m => m.EstatusID == id);
            if (estatusPedido == null)
            {
                return NotFound();
            }

            return View(estatusPedido);
        }

        // POST: EstatusPedido/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            ViewData["Categorias"] = (from c in _context.Categorias select c);
            var estatusPedido = await _context.EstatusPedido.FindAsync(id);
            _context.EstatusPedido.Remove(estatusPedido);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EstatusPedidoExists(int id)
        {
            return _context.EstatusPedido.Any(e => e.EstatusID == id);
        }
    }
}

ProyectoFinal/Controllers/ProductosController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Proyecto.Models;
using ProyectoFinal.Data;

namespace ProyectoFinal.Controllers
{
    //[Authorize(Roles = "Administrador")]
    public class ProductosController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ProductosController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Productos
        public async Task<IActionResult> Index()
        {
            ViewData["Categorias"] = (from c in _context.Categorias select c);

            var applicationDbContext = _context.Productos.Include(p => p.Categorias);
            return View(await applicationDbContext.ToListAsync());
        }
        
        // LISTAMOS LOS PRODUCTOS POR SU CATEGORIA
        public IActionResult Listar(int CategoriaID)
        {
            ViewData["Categorias"] = (from c in _context.Categorias select c);

            var productosCategoria = (from pc in _context.Productos.Include("Categorias")
                                      where pc.CategoriaID == CategoriaID
                                      select pc).ToList();
            return View(productosCategoria);
        }

        // GET: Productos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            ViewData["Categorias"] = (from c in _context.Categorias select c);

            if (id == null)
            {
                return NotFound();
            }

            var productos = await _context.Productos
                .Include(p => p.Categorias)
                .FirstOrDefaultAsync(m => m.ProductoID == id);
            if (productos == null)
            {
                return NotFound();
            }

            return View(productos);
        }

        // GET: Productos/Create
        public IActionResult Create()
        {
            ViewData["Categorias"] = (from c in _context.Categorias select c);

            ViewData["CategoriaID"] = new SelectList(_context.Categorias, "CategoriaID", "NombreCategoria");
            return View();
        }

        // POST: Productos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ProductoID,NombreProducto,Existencia,Precio,Descontinuado,Image,CategoriaID")] Productos productos, IList<IFormFile> Image)
        {
            ViewData["Categorias"] = (from c in _context.Categorias select c);

            if (ModelState.IsValid)
            {
                foreach (var item in Image)
                {
                    if (item.Length>0)
                    {
                        using (var stream = new MemoryStream())
                        {
                            await item.CopyToAsync(stream);
                            productos.Image = stream.ToArray();
                        }
                    }
                }
                _context.Add(productos);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoriaID"] = new SelectList(_context.Categorias, "CategoriaID", "NombreCategoria", productos.CategoriaID);
            return View(productos);
        }

        // GET: Productos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            ViewData["Categorias"] = (from c in _context.Categorias select c);

            if (id == null)
            {
                return NotFound();
            }

            var productos = await _context.Productos.FindAsync(id);
            if (productos == null)
            {
                return NotFound();
            }
            ViewData["CategoriaID"] = new SelectList(_context.Categorias, "CategoriaID", "NombreCategoria", productos.CategoriaID);
            return View(productos);
        }

        // POST: Productos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ProductoID,NombreProducto,Existencia,Precio,Descontinuado,Image,CategoriaID")] Productos productos)
        {
            ViewData["Categorias"] = (from c in _context.Categorias select c);

            if (id != productos.ProductoID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(productos);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductosExists(productos.ProductoID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoriaID"] = new SelectList(_context.Categorias, "CategoriaID", "NombreCategoria", productos.CategoriaID);
            return View(productos);
        }

        // GET: Productos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            ViewData["Categorias"] = (from c in _context.Categorias select c);

            if (id == null)
            {
                return NotFound();
            }

            var productos = await _context.Productos
                .Include(p => p.Categorias)
                .FirstOrDefaultAsync(m => m.ProductoID == id);
            if (productos == null)
            {
                return NotFound();
            }

            return View(productos);
        }

        // POST: Productos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            ViewData["Categorias"] = (from c in _context.Categorias select c);

            var productos = await _context.Productos.FindAsync(id);
            _context.Productos.Remove(productos);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductosExists(int id)
        {
            return _context.Productos.Any(e => e.ProductoID == id);
        }
    }
}

ProyectoFinal/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using Proyecto.Models
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager


<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


    <title>Proyecto Final Ventas</title>
    <link rel="shortcut icon" type="image/x-icon" href="~/images/miLogo.png">

    <!-- jQuery -->
    <script src="~/js/jquery-2.0.0.min.js" type="text/javascript"></script>

    <!-- Bootstrap4 files-->
    <script src="~/js/bootstrap.bundle.min.js" type="text/javascript"></script>
    <link href="~/css/bootstrap.css?v=1.0" rel="stylesheet" type="text/css" />

    <!-- Style for Card-Promo-->
    <link href="~/css/card_promo.css" rel="stylesheet" type="text/css" />
    <!-- Style and JavaScript for Slider-->
    <link href="~/css/slider.css" rel="stylesheet" type="text/css" />
    <script src="~/js/slider.js" type="text/javascript"></script>

    <!-- Font awesome 5 -->
    <link href="~/fonts/fontawesome/css/fontawesome-all.min.css" type="text/css" rel="stylesheet">

    <!-- Social Media icons -->
    <link rel="stylesheet" href="./vendors/fontastic/styles.css">

    <!-- plugin: fancybox  -->
    <script src="~/plugins/fancybox/fancybox.min.js" type="text/javascript"></script>
    <link href="~/plugins/fancybox/fancybox.min.css" type="text/css" rel="stylesheet">

    <!-- plugin: owl carousel  -->
    <link href="~/plugins/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">
    <link href="~/plugins/owlcarousel/assets/owl.theme.default.css" rel="stylesheet">
    <script src="~/plugins/owlcarousel/owl.carousel.min.js"></script>

    <!-- custom style -->
    <link href="~/css/ui.css?v=1.0" rel="stylesheet" type="text/css" />
    <link href="~/css/responsive.css" rel="stylesheet" media="only screen and (max-width: 1200px)" />

    <!-- custom javascript -->
    <script src="~/js/script.js" type="text/javascript"></script>

    <script type="text/javascript">
        /// some script

        // jquery ready start
        $(document).ready(function () {
            // jQuery code

        });
// jquery end
    </script>
</head>
<body>
    <header class="section-header">
        <section class="header-main">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-lg-3">
                        <div class="brand-wrap">
                            <img class="logo" width="200" height="350" src="~/images/miLogo.png">
                        </div> <!-- brand-wrap.// -->
                    </div>
                    <div class="col-lg-6 col-sm-6">
                        <form action="#" class="search-wrap">
                            <div class="input-group">
                                <input type="text" class="form-control" placeholder="Buscar">
                                <div class="input-group-append">
                                    <button class="btn btn-primary" type="submit">
                                        <i class="fa fa-search"></i>
                                    </button>
                                </div>
                            </div>
                        </form> <!-- search-wrap .end// -->
                    </div> <!-- col.// -->
                    <div class="col-lg-3 col-sm-6">
                        <div class="widgets-wrap d-flex justify-content-end">
                            <div class="widget-header">
                                <a href="@Url.Action("Index", "Carrito")" class="icontext">
                                    <div class="icon-wrap icon-xs bg2 round text-secondary"><i class="fa fa-shopping-cart"></i></div>
                                    <div class="text-wrap">
                                        <small>Carrito</small>
                                        <span> @ViewData["ProductoID"] Articulos</span>
                                    </div>
                                </a>
                            </div> <!-- widget .// -->
                            <div class="widget-header dropdown">
                                <a href="~/Identity/Account/Login" class="ml-3 icontext"  data-offset="20,10">
                                    <div class="icon-wrap icon-xs bg2 round text-secondary"><i class="fa fa-user"></i></div>
                                    <div class="text-wrap">
                                        <small>Bienvenido</small>
                                        <span> Iniciar Sesión</span><!--<span>Iniciar Sesión <i class="fa fa-caret-down"></i></span>-->
                                    </div>
                                </a>
                                <div class="dropdown-menu dropdown-menu-right">

                                    <form class="px-4 py-3">
                                        <div class="form-group">
                                            <label>Correo Electrónico</label>
                                            <input type="email" class="form-control" placeholder="correo@ejemplo.com">
                                        </div>
                                        <div class="form-group">
                                            <label>Contraseña</label>
                                            <input type="password" class="form-control" placeholder="Contraseña">
                                        </div>
                                        <button type="submit" class="btn btn-primary">Iniciar Sesión</button>
                                    </form>
                                    <hr class="dropdown-divider">
                                    <a class="dropdown-item" href="#">Ya tiene una cuenta? Iniciar Sesión</a>
                                    <a class="dropdown-item" href="#">Olvidó su contraseña?</a>
                                </div> <!--  dropdown-menu .// -->
                            </div> <!-- widget  dropdown.// -->
                        </div>	<!-- widgets-wrap.// -->
                    </div> <!-- col.// -->
                </div> <!-- row.// -->
            </div> <!-- container.// -->
        </section> <!-- header-main .// -->

        @if (User.IsInRole("Administrador"))
        {
            <nav class="navbar navbar-expand-lg navbar-dark bg-secondary">
                <div class="container">

                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#main_nav" aria-controls="main_nav" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="collapse navbar-collapse" id="main_nav">
                        <ul class="navbar-nav">
                            <li class="nav-item">
                                <a class="nav-link" href="@Url.Action("Index", "Productos")">Productos</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="@Url.Action("Index", "Promociones")">Promociones</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="@Url.Action("Index", "Categorias")">Categorias</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="@Url.Action("Index", "EstatusPedido")">Estatus</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="@Url.Action("Index", "Pedidos")">Pedidos</a>
                            </li>
                        </ul>
                    </div> <!-- collapse .// -->
                </div> <!-- container .// -->
            </nav>
        }
        else
        {
            <nav class="navbar navbar-expand-lg navbar-dark bg-secondary">
                <div class="container">

                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#main_nav" aria-controls="main_nav" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="collapse navbar-collapse" id="main_nav">
                        <ul class="navbar-nav">
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown07" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Categorias</a>
                                <div class="dropdown-menu" aria-labelledby="dropdown07">
                                    @foreach (var categoria in ViewBag.Categorias)
                                    {
                                        <a class="dropdown-item" href="@Url.Action("Listar", "Productos", new { CategoriaID = @categoria.CategoriaID })">@categoria.NombreCategoria</a>
                                    }
                                    </div>
                            </li>
                            @if (User.Identity.IsAuthenticated)
                            {
                                <li class="nav-item">
                                    <a class="nav-link" href="@Url.Action("PedidosCliente", "Pedidos")">Mis Pedidos</a>
                                </li>
                            }
                            <li class="nav-item">
                                <a class="nav-link" href="#">Quienes Somos</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">Contactanos</a>
                            </li>
                            <!--<li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown07" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Otros</a>
                                <div class="dropdown-menu" aria-labelledby="dropdown07">
                                    <a class="dropdown-item" href="#">Alimentos y Bebidas</a>
                                    <a class="dropdown-item" href="#">Videojuegos</a>
                                </div>
                            </li>-->
                        </ul>
                    </div> <!-- collapse .// -->
                </div> <!-- container .// -->
            </nav>
        }

    </header> <!-- section-header.// -->

    @RenderBody()


    @RenderSection("Scripts", required: false)
</body>
</html>